### ISSUE TITLE
ApplicationDefaultCredentialsError on AWS

### ISSUE THREAD

**Issue by danielfaust** [google/identity-toolkit-python-client#12]
Apparently the changes introduced two days ago in gitkitclient.py and rpchelper.py (Add support to use Google application default credential) are not backwards compatible.

When running code which worked on AWS in version 0.1.8, that code is now throwing an error in version 0.1.9.

      Traceback (most recent call last):
        File "SERVER.py", line 161, in <module>
          settings['key']
        File "/home/USER/VENV/local/lib/python2.7/site-packages/identitytoolkit/gitkitclient.py", line 192, in __init__
          use_app_default_credentials)
        File "/home/USER/VENV/local/lib/python2.7/site-packages/identitytoolkit/rpchelper.py", line 50, in __init__
          self.credentials = GoogleCredentials.get_application_default() \
        File "/home/USER/VENV/local/lib/python2.7/site-packages/oauth2client/client.py", line 1319, in get_application_default
          return GoogleCredentials._get_implicit_credentials()
        File "/home/USER/VENV/local/lib/python2.7/site-packages/oauth2client/client.py", line 1309, in _get_implicit_credentials
          raise ApplicationDefaultCredentialsError(ADC_HELP_MSG)
      ApplicationDefaultCredentialsError: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.

After modifying the call to gitkitclient.GitkitClient by adding `use_app_default_credentials=True` and removing the service account key as a parameter, I'm now getting

    ApplicationDefaultCredentialsError: An error was encountered while reading json file: ../FILENAME-DOWNLOADED-FILE.p12 (pointed to by GOOGLE_APPLICATION_CREDENTIALS environment variable): Extra data: line 1 column 2 - line 11 column 21 (char 1 - 2572)

Is it safe to set `use_app_default_credentials` to `False`? What is the content of the GOOGLE_APPLICATION_CREDENTIALS? Isn't it the p12 file which can be downloaded from the developer console, the one which was the servive account key?

Ok, it's the json file that can be generated and downloaded from the developer console. Now, the question that remains is the following: Is it safe to set `use_app_default_credentials` to `False`?

**Comment by wuyanna** [comment]
Yes, it should be False if it's not on Google App Engine/Cloud Engine. Thanks for pointing out this error. I will change the default value of use_app_default_credentials to False.

**Comment by danielfaust** [comment]
Ok, thanks. But I've managed to set it to true when using the downloadable json file and adjusting that env variable to point to the json file. My question then is, if there is any difference in security strength between using False or True+JSON? Because it then might be the case, that people will just thing "oh, it's not needed anyway". At least a warning should then appear when using "use_app_default_credentials=False"

**Comment by danielfaust** [comment]
Additionally, now the docs are out of sync: https://github.com/google/identity-toolkit-python-client#initialize-gitkit-client-instance

**Comment by wuyanna** [comment]
The security enhance is that if the environment variable is set on host machines, there's no need to provide service account credentials in the code, which makes it less likely for some careless developers to expose their credentials in their code on a public repository like Github.

Additionally, Google App Engine/Cloud Engine already set this environment variable for each project, so there's no need for developers to provide any service account credentials if they are using GAE/GCE. The purpose of this change is to simplify the work of using Identity Toolkit on GAE/GCE, therefore, it shouldn't have affected existing users. I will fix the backward-compatibility problem and update the doc shortly.

**Comment by danielfaust** [comment]
Ok, but if use_app_default_credentials=False doesn't use any credentials at all, how could that be a sensible default? v0.1.8 made you use the p12 file which gets replaced by the json file if use_app_default_credentials=True. In that case, it would make more sense not to remove the server_api_key kwarg (for backwards compatibility, but with serious warnings), but just add the use_app_default_credentials kwarg and use that if it is provided.

**Comment by danielfaust** [comment]
This `server_api_key` is the same as the `private_key` in the JSON file, but stored as a PFX files, right?

If you say that `server_api_key` is no longer used, then this implies that the `private_key` in the JSON file is also irrelevant. The `private_key` may be relevant for the oauth2client initialization, but not for the communication to the authentication server, you say?

Because if this is **not** true, then I don't understand how the GitkitClient is able to work without any private key at all (`server_api_key` not required)

Then the only credentials needed are `client_email` and the `client_id`, and those are getting "protected" py putting them in the file pointed to via `GOOGLE_APPLICATION_CREDENTIALS`?

I just called `gitkitclient.GitkitClient()` without any parameters, but having the `GOOGLE_APPLICATION_CREDENTIALS` variable set, and it worked flawlessly. Is that the intention of the modification? To move `client_email` and `client_id` out of the code? Wouldn't it then be better to remove the `use_app_default_credentials` keyword altogether, check if `client_email` and the `client_id` are set, and if they are, perform a non-default-credentials initialization, and if not, then check if the `GOOGLE_APPLICATION_CREDENTIALS` exists and use that, otherwise raise an exception?

The private key is really not getting used by Gitkit? I thought it was required for signing messages sent to Googles authentication servers.

**Comment by wuyanna** [comment]
`server_api_key` is not the private key in the JSON file you download, it's just an API key with little security protection that the library used to use when making trivial API calls which don't require service account credentials, namely `/publicKeys` API, and the API key is no longer needed now to call `/publicKeys`, so I cleaned it up in the code. All the other API calls, such as `deleteUsers` or `uploadUsers` require service account email and private key.

The intention of this change is merely to make it easier for App Engine users by not requiring them to set service account email and private key manually. So in your case, you don't need to make any changes to your old code once we change the default value of the flag to `False`. But if you really want to use the new default credential feature, then what you have done now is correct, except that you need to set the `use_app_default_credentials` to `True` after we change the default value to `False`. 

It's a good point that you proposed to remove the flag and check whether service account email and private key are set. However, I added this flag due to the fact that service account email and private key are not strictly required by `GitkitClient`, you can still have a working auth server if you don't need the feature to manually manage your users(e.g. delete users, upload users, get oob code...). That's also why in the previous code, it didn't check whether an empty value is passed in in `__init__`. If the flag was removed, then the intention of passing in an empty service account credential would be ambiguous, it could either mean that the developer doesn't want to use a service account or they want to use default credentials. Therefore, I added this flag to allow developers to choose what they really want.

**Comment by RevolutionTech** [comment]
Please upgrade `identity-toolkit-python-client` to `0.1.10`. We believe that your issues should be resolved in this version.
