### ISSUE TITLE
Missing verifyEmail Action

### ISSUE THREAD

**Issue by alexodus** [google/identity-toolkit-python-client#5]
Please insert "verifyEmail" action like in go client

**Comment by liujin-google** [comment]
Hi alexodus, the python client provides a public method GetEmailVerificationLink(email) which is expected to be called from your server, since the Identity Toolkit Javascript widget does not provide a UI to trigger the email verification flow.

Do you need other features that are missing from the GetEmailVerificationLink() method?

**Comment by alexodus** [comment]
Oops! I had missed this function. Thanks and sorry
